#!/usr/bin/env bash
set -euo pipefail

DEVENV_SCRIPT_NAME="other_tools"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/utils.sh"

# Exit if not Linux
if [[ "$(uname -s)" != "Linux" ]]; then
  echo "This script supports only Linux. Detected: $(uname -s). Aborting."
  exit 1
fi

get_ghostty_version() {
  # Prefer --version, but keep +version fallback for older builds that only expose it.
  ghostty --version 2>/dev/null || ghostty +version 2>/dev/null || echo "version check failed"
}

install_ghostty_wsl() {
  if ! is_wsl; then
    echo "WSL not detected. Skipping Ghostty setup."
    return 0
  fi

  if command -v ghostty >/dev/null 2>&1; then
    echo "Ghostty is already installed: $(get_ghostty_version)"
    return 0
  fi

  echo "WSL detected. Installing Ghostty build dependencies..."
  sudo apt-get update -y
  sudo apt-get install -y \
    git curl pkg-config cmake scdoc gettext \
    libgtk-4-dev libadwaita-1-dev libxkbcommon-dev \
    libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libpng-dev \
    zig

  local zig_version
  zig_version="$(zig version 2>/dev/null || true)"
  if [[ -z "$zig_version" ]]; then
    echo "ERROR: zig is not available after installation." >&2
    return 1
  fi
  echo "Using zig version: $zig_version"

  local ghostty_repo="$HOME/.local/src/ghostty"
  local ghostty_bin="$HOME/.local/bin/ghostty"

  mkdir -p "$HOME/.local/src" "$HOME/.local/bin"

  if [[ -d "$ghostty_repo/.git" ]]; then
    echo "Ghostty source already present. Updating..."
    if ! git -C "$ghostty_repo" pull --ff-only; then
      echo "ERROR: failed to update Ghostty source repository at $ghostty_repo." >&2
      return 1
    fi
  else
    echo "Cloning Ghostty source..."
    if ! git clone https://github.com/ghostty-org/ghostty "$ghostty_repo"; then
      echo "ERROR: failed to clone Ghostty source repository into $ghostty_repo." >&2
      return 1
    fi
  fi

  echo "Building Ghostty from source..."
  if ! (
    cd "$ghostty_repo"
    zig build -Doptimize=ReleaseFast
  ); then
    echo "ERROR: Ghostty build failed." >&2
    return 1
  fi

  if [[ -x "$ghostty_repo/zig-out/bin/ghostty" ]]; then
    install -m 0755 "$ghostty_repo/zig-out/bin/ghostty" "$ghostty_bin"
    echo "Ghostty installed at $ghostty_bin"
  else
    echo "ERROR: Ghostty build finished, but binary not found at zig-out/bin/ghostty." >&2
    return 1
  fi
}

configure_ghostty_wsl() {
  if ! is_wsl; then
    return 0
  fi

  local path_line="export PATH=\"\$HOME/.local/bin:\$PATH\""
  append_once_to_file "$HOME/.zshrc" "$path_line"
  append_once_to_file "$HOME/.bashrc" "$path_line"
  export PATH="$HOME/.local/bin:$PATH"

  local ghostty_config_dir="$HOME/.config/ghostty"
  local ghostty_config_file="$ghostty_config_dir/config"
  local default_shell

  if [[ -x /usr/bin/zsh ]]; then
    default_shell="/usr/bin/zsh"
  else
    default_shell="/bin/bash"
  fi

  mkdir -p "$ghostty_config_dir"
  if [[ ! -f "$ghostty_config_file" ]]; then
    # Ghostty config expects an unquoted command path value for this key.
    cat >"$ghostty_config_file" <<EOF
# Generated by devenv for WSL use.
command = ${default_shell}
font-size = 12
confirm-close-surface = false
EOF
    echo "Created Ghostty config at $ghostty_config_file"
  elif ! grep -Eq '^[[:space:]]*command[[:space:]]*=' "$ghostty_config_file"; then
    {
      echo ""
      echo "# Added by devenv for WSL use."
      echo "command = ${default_shell}"
    } >>"$ghostty_config_file"
    echo "Updated Ghostty config with default shell at $ghostty_config_file"
  fi
}

install_k6() {
  if command -v k6 >/dev/null 2>&1; then
    echo "k6 is already installed: $(k6 version)"
    return 0
  fi

  echo "Installing k6..."

  sudo mkdir -p /usr/share/keyrings
  curl --retry 3 --max-time 60 -fsSL https://dl.k6.io/key.gpg \
    | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg

  echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] \
    https://dl.k6.io/deb stable main" \
    | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null

  sudo apt-get update -y
  sudo apt-get install -y k6

  echo "k6 installed: $(k6 version)"
}

main() {
  install_ghostty_wsl
  configure_ghostty_wsl
  install_k6

  echo "===================="
  echo "Installed tool versions"
  echo "===================="
  if command -v ghostty >/dev/null 2>&1; then
    echo "ghostty: $(get_ghostty_version)"
  else
    echo "ghostty: not installed"
  fi
  k6 version || echo "k6: not installed"
}

main
